apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: AZURE_EVENTHUB_CONNECTION_STRING
    - name: storageAccountName
      secretKeyRef:
        name: AZURE_EVENTHUB_STORAGE_ACCOUNT_NAME
    - name: storageAccountKey
      secretKeyRef:
        name: AZURE_EVENTHUB_STORAGE_ACCOUNT_KEY
    - name: storageContainerName
      secretKeyRef:
        name: AZURE_EVENTHUB_STORAGE_ACCOUNT_CONTAINER_NAME
auth:
  secretStore: envvar-secret-store

