@publisher-service = localhost:5100

### Create an order via order-service POST
POST http://{{publisher-service}}/weatherForecast
Content-Type: application/json

{
    "oldWeatherState" : "Hot",
    "currentWeatherState" : "Freezing"
}
